package main

import (
	"os"
	"path/filepath"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	Provider map[string]Provider `toml:"provider"`
	Active   ActiveConfig        `toml:"active"`
}

type Provider struct {
	BaseURL    string   `toml:"base_url"`
	APIKey     string   `toml:"api_key,omitempty"`
	UseKeyring bool     `toml:"use_keyring"`
	Presets    []Preset `toml:"preset"`
}

type Preset struct {
	Name          string `toml:"name"`
	ModelID       string `toml:"model_id"`
	ModelName     string `toml:"model_name"`
	ModelDesc     string `toml:"model_desc,omitempty"`
	DefaultFor    string `toml:"default_for,omitempty"`
	OpenAIAPIType string `toml:"openai_api_type,omitempty"`
}

type ActiveConfig struct {
	Name      string `toml:"name"`
	Provider  string `toml:"provider"`
	ModelID   string `toml:"model_id"`
	ModelName string `toml:"model_name"`
}

func DefaultConfigPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "modelswitch", "config.toml")
}

func DefaultActiveEnvPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".claude", "active-env.sh")
}

func LoadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return &Config{
			Provider: make(map[string]Provider),
			Active:   ActiveConfig{},
		}, nil
	}
	var cfg Config
	if err := toml.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	if cfg.Provider == nil {
		cfg.Provider = make(map[string]Provider)
	}
	return &cfg, nil
}

func SaveConfig(path string, cfg *Config) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	// Strip APIKey from providers that use keyring
	sanitized := *cfg
	sanitized.Provider = make(map[string]Provider, len(cfg.Provider))
	for name, p := range cfg.Provider {
		if p.UseKeyring {
			p.APIKey = ""
		}
		sanitized.Provider[name] = p
	}
	data, err := toml.Marshal(&sanitized)
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0600)
}

func WriteActiveEnv(path string, cfg *Config, preset *Preset, providerName string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	p := cfg.Provider[providerName]

	// Determine the base URL to use
	baseURL := p.BaseURL
	if baseURL == "" {
		switch providerName {
		case "openrouter":
			baseURL = "https://openrouter.ai/api"
		case "anthropic":
			baseURL = "https://api.anthropic.com"
		case "openai":
			baseURL = "https://api.openai.com/v1"
		}
	}

	env := "# Generated by modelswitch — source this file: source " + path + "\n"
	env += "export ANTHROPIC_BASE_URL=\"" + baseURL + "\"\n"
	apiKey, _ := ResolveAPIKey(providerName, p)
	env += "export ANTHROPIC_API_KEY=\"" + apiKey + "\"\n"
	env += "export ANTHROPIC_DEFAULT_OPUS_MODEL=\"" + preset.ModelID + "\"\n"
	env += "export ANTHROPIC_DEFAULT_SONNET_MODEL=\"" + preset.ModelID + "\"\n"
	env += "export ANTHROPIC_DEFAULT_HAIKU_MODEL=\"" + preset.ModelID + "\"\n"

	return os.WriteFile(path, []byte(env), 0600)
}

// MigratePlaintextKeys moves any plaintext API keys from config to the system keyring.
func MigratePlaintextKeys(cfg *Config) error {
	migrated := false
	for name, p := range cfg.Provider {
		if p.APIKey != "" && !p.UseKeyring {
			if err := KeyringSet(name, p.APIKey); err == nil {
				p.UseKeyring = true
				p.APIKey = ""
				cfg.Provider[name] = p
				migrated = true
			}
		}
	}
	if migrated {
		return SaveConfig(DefaultConfigPath(), cfg)
	}
	return nil
}
