package main

import (
	"os"
	"path/filepath"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	Provider map[string]Provider `toml:"provider"`
	Active   ActiveConfig        `toml:"active"`
}

type Provider struct {
	BaseURL    string   `toml:"base_url"`
	APIKey     string   `toml:"api_key,omitempty"`
	UseKeyring bool     `toml:"use_keyring"`
	Presets    []Preset `toml:"preset"`
}

type Preset struct {
	Name          string `toml:"name"`
	ModelID       string `toml:"model_id"`
	ModelName     string `toml:"model_name"`
	ModelDesc     string `toml:"model_desc,omitempty"`
	DefaultFor    string `toml:"default_for,omitempty"`
	OpenAIAPIType string `toml:"openai_api_type,omitempty"`
}

type ActiveConfig struct {
	Name      string `toml:"name"`
	Provider  string `toml:"provider"`
	ModelID   string `toml:"model_id"`
	ModelName string `toml:"model_name"`
}

// ProviderInfo describes a known LLM provider with Anthropic-compatible API.
type ProviderInfo struct {
	Name             string
	DisplayName      string
	DefaultURL       string
	AuthVar          string // "ANTHROPIC_API_KEY" or "ANTHROPIC_AUTH_TOKEN"
	Description      string
	NeedsEmptyAPIKey bool   // Set ANTHROPIC_API_KEY="" alongside the auth token
	SupportsBrowse   bool   // Supports fetching live model list (OpenRouter only)
}

// KnownProviders returns the list of built-in providers.
func KnownProviders() []ProviderInfo {
	return []ProviderInfo{
		{
			Name: "openrouter", DisplayName: "OpenRouter",
			DefaultURL: "https://openrouter.ai/api",
			AuthVar: "ANTHROPIC_AUTH_TOKEN", Description: "400+ models from every major provider",
			NeedsEmptyAPIKey: true, SupportsBrowse: true,
		},
		{
			Name: "anthropic", DisplayName: "Anthropic",
			DefaultURL: "https://api.anthropic.com",
			AuthVar: "ANTHROPIC_API_KEY", Description: "Claude models by Anthropic",
		},
		{
			Name: "deepseek", DisplayName: "DeepSeek",
			DefaultURL: "https://api.deepseek.com/anthropic",
			AuthVar: "ANTHROPIC_API_KEY", Description: "DeepSeek V4 Flash & Pro",
		},
		{
			Name: "kimi", DisplayName: "Kimi",
			DefaultURL: "https://api.moonshot.ai/anthropic",
			AuthVar: "ANTHROPIC_AUTH_TOKEN", Description: "Kimi K2/K2.5 by Moonshot AI",
		},
		{
			Name: "zai", DisplayName: "Z.AI",
			DefaultURL: "https://api.z.ai/api/anthropic",
			AuthVar: "ANTHROPIC_AUTH_TOKEN", Description: "GLM-4.7/5 by ZhipuAI",
		},
		{
			Name: "minimax", DisplayName: "MiniMax",
			DefaultURL: "https://api.minimax.io/anthropic",
			AuthVar: "ANTHROPIC_AUTH_TOKEN", Description: "MiniMax M2.5/M2.1",
		},
		{
			Name: "ollama", DisplayName: "Ollama",
			DefaultURL: "http://localhost:11434",
			AuthVar: "ANTHROPIC_API_KEY", Description: "Local models via Ollama",
		},
	}
}

// ProviderInfoFor looks up a known provider by name.
func ProviderInfoFor(name string) (ProviderInfo, bool) {
	for _, p := range KnownProviders() {
		if p.Name == name {
			return p, true
		}
	}
	return ProviderInfo{}, false
}

// IsKnownProvider returns true if name matches a built-in provider.
func IsKnownProvider(name string) bool {
	_, ok := ProviderInfoFor(name)
	return ok
}

func DefaultConfigPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "modelswitch", "config.toml")
}

func DefaultActiveEnvPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".claude", "active-env.sh")
}

func LoadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return &Config{
			Provider: make(map[string]Provider),
			Active:   ActiveConfig{},
		}, nil
	}
	var cfg Config
	if err := toml.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	if cfg.Provider == nil {
		cfg.Provider = make(map[string]Provider)
	}
	return &cfg, nil
}

func SaveConfig(path string, cfg *Config) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	// Strip APIKey from providers that use keyring
	sanitized := *cfg
	sanitized.Provider = make(map[string]Provider, len(cfg.Provider))
	for name, p := range cfg.Provider {
		if p.UseKeyring {
			p.APIKey = ""
		}
		sanitized.Provider[name] = p
	}
	data, err := toml.Marshal(&sanitized)
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0600)
}

func WriteActiveEnv(path string, cfg *Config, preset *Preset, providerName string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	p := cfg.Provider[providerName]

	// Determine the base URL to use
	baseURL := p.BaseURL
	if baseURL == "" {
		if info, ok := ProviderInfoFor(providerName); ok {
			baseURL = info.DefaultURL
		}
	}

	env := "# Generated by modelswitch — source this file: source " + path + "\n"
	env += "export ANTHROPIC_BASE_URL=\"" + baseURL + "\"\n"

	apiKey, _ := ResolveAPIKey(providerName, p)

	// Use the correct auth variable for this provider
	if info, ok := ProviderInfoFor(providerName); ok && info.AuthVar == "ANTHROPIC_AUTH_TOKEN" {
		env += "export ANTHROPIC_AUTH_TOKEN=\"" + apiKey + "\"\n"
		if info.NeedsEmptyAPIKey {
			env += "export ANTHROPIC_API_KEY=\"\"\n"
		}
	} else {
		env += "export ANTHROPIC_API_KEY=\"" + apiKey + "\"\n"
	}

	env += "export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1\n"
	env += "export ANTHROPIC_DEFAULT_OPUS_MODEL=\"" + preset.ModelID + "\"\n"
	env += "export ANTHROPIC_DEFAULT_SONNET_MODEL=\"" + preset.ModelID + "\"\n"
	env += "export ANTHROPIC_DEFAULT_HAIKU_MODEL=\"" + preset.ModelID + "\"\n"

	return os.WriteFile(path, []byte(env), 0600)
}

// MigratePlaintextKeys moves any plaintext API keys from config to the system keyring.
func MigratePlaintextKeys(cfg *Config) error {
	migrated := false
	for name, p := range cfg.Provider {
		if p.APIKey != "" && !p.UseKeyring {
			if err := KeyringSet(name, p.APIKey); err == nil {
				p.UseKeyring = true
				p.APIKey = ""
				cfg.Provider[name] = p
				migrated = true
			}
		}
	}
	if migrated {
		return SaveConfig(DefaultConfigPath(), cfg)
	}
	return nil
}
